<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description , arguments+ , outputs* , example* , bugs* , reporting* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (output* , explanation*)*>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
	<name>mri_watershed</name>
	<synopsis>mri_watershed [&lt;options&gt;] invol outvol</synopsis>
	<description>This program strips skull and other outer non-brain tissue and produces the brain volume from T1 volume or the scanned volume.

The "watershed" segmentation algorithm was used to dertermine the intensity values for white matter, grey matter, and CSF. 
A force field was then used to fit a spherical surface to the brain. The shape of the surface fit was then evaluated against a previously derived template. 

If you used -atlas option, then { The template was used to correct the surface. }

The finely grained sphere was fit to the brain.

The default parameters are: -w 0.82 -b 0.32 -h 10 -seedpt -ta -wta 
You can use one of the first five flags to change these default parms.

(Segonne 2004)</description>
  <arguments>
    <positional>
      <argument>invol</argument>
      <explanation>input volume</explanation>
      <argument>outvol</argument>
      <explanation>output volume</explanation>
    </positional>
    <required-flagged>
      <intro>None</intro>
    </required-flagged>
    <optional-flagged>
      <argument>-w weight</argument>
      <explanation>preweight the input image using atlas information (no_w -> 1)</explanation> 
      <argument>-no_wta</argument>
      <explanation>dont use the preweighting fot the template deformation</explanation> 
      <argument>-b proba_merging</argument>
      <explanation>use the basins merging using atlas information (no_b -> 1)</explanation> 
      <argument>-h int_hpf</argument>
      <explanation>presize the preflooding height (in percent)</explanation> 
      <argument>-no_seedpt</argument>
      <explanation>dont use (seedpoints using atlas information)</explanation> 
      <argument>-no-ta</argument>
      <explanation>dont use (template deformation using atlas information)</explanation> 
      <argument>-copy</argument>
      <explanation>Just copy input to output, ignore other options</explanation> 


      <argument>-atlas</argument>
      <explanation>use the atlas information to correct the segmentation. When the segmented brain is not correct, this option might help you.</explanation> 
      <argument>-surf [surfname]</argument>
      <explanation>save the BEM surfaces.In order to get the surfaces consistent with tkmedit, you have to use the option -useSRAS.</explanation> 
      <argument>-useSRAS</argument>
      <explanation>use the surface RAS coordinates (not the scanner RAS) for surfaces.</explanation> 
      <argument>-noT1</argument>
      <explanation>don't do T1 analysis. (Useful when running out of memory)</explanation> 
      <argument>-less</argument>
      <explanation>shrink the surface</explanation> 
      <argument>-more</argument>
      <explanation>expand the surface</explanation> 
      <argument>-wat</argument>
      <explanation>use only the watershed algorithm</explanation> 
      <argument>-T1</argument>
      <explanation>specify T1 input volume (T1 grey value = 110)</explanation> 
      <argument>-wat+temp</argument>
      <explanation>watershed algo and first template smoothing</explanation> 
      <argument>-first_temp</argument>
      <explanation>use only the first template smoothing + local matching</explanation> 
      <argument>-surf_debug</argument>
      <explanation>visualize the surfaces onto the output volume</explanation> 
      <argument>-brainsurf [surfname]</argument>
      <explanation>save the brain surface</explanation> 
      <argument>-shk_br_surf [int_h surfname]</argument>
      <explanation>to save the brain surface shrank inward of int_h mm</explanation> 
      <argument>-s [int_i int_j int_k]</argument>
      <explanation>add a seed point</explanation> 
      <argument>-c [int_i int_j int_k]</argument>
      <explanation>specify the center of the brain (in voxel unit)</explanation> 
      <argument>-r int_r</argument>
      <explanation>specify the radius of the brain (in voxel unit)</explanation> 
      <argument>-t int_threshold</argument>
      <explanation>change the threshold in the watershed analyze process</explanation> 
      <argument>-h int_hpf</argument>
      <explanation>precize the preflooding height (in percent)</explanation> 
      <argument>-n</argument>
      <explanation>not use the watershed analyze process</explanation> 
      <argument>-LABEL</argument>
      <explanation>labelize the output volume into scalp, skull, csf, gray and white</explanation> 
      <argument>-man [int_csf int_trn int_gray]</argument>
      <explanation>to change the different parameters csf_max, transition_intensity and GM_intensity</explanation> 
      <argument>-xthresh xthresh</argument>
      <explanation>Remove voxels whose intensity exceeds xthresh</explanation> 
      <argument>-mask</argument>
      <explanation>mask a volume with the brain mask</explanation> 
      <argument>--help</argument>
      <explanation>show usage message</explanation> 
      <argument>--version</argument>
      <explanation>show the current version</explanation> 
    </optional-flagged>
  </arguments>
  <outputs>
    <output>brainvol</output>
    <explanation>skull stripped brain volume</explanation>
    <output>BEMsurfaces</output>
    <explanation>when you specify the option -brainsurf surfname</explanation>
  </outputs>
	<example>mri-watershed -atlas T1 brain

where T1 is the T1 volume and brain is the output brain volume. When the cerebellum is cut-off from the brain or getting the left/right asymmetric brain, you should first try this -atlas option.</example>
	<example>mri-watershed T1 brain

The same as the first example, but no correction is applied to the intermediate result.</example>
  <reporting>Report bugs to &lt;freesurfer@nmr.mgh.harvard.edu&gt;</reporting>
	<see-also>mri_normalize</see-also>
</help>

