<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description , arguments+ , outputs* , 
example* , bugs* , reporting* , references* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (intro* , argument* , explanation*)*>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
	<name>infant_recon_all</name>
	<synopsis>infant_recon_all [&lt;options&gt;] </synopsis>
	<description>This program performs recon-all on infants (0-2yrs). Cite Zöllei et al., FreeSurfer image processing pipeline for infant clinical MRI images, 
HBM2017, Vancouver, Canada while journal submission is pending. Make sure that SUBJECTS_DIR is properly set before calling this script. </description>
  <arguments>

    <positional>
      <intro>None</intro>
    </positional>

    <required-flagged>

      <argument>--s subjid</argument>
      <explanation>FreeSurfer subject name as found in $SUBJECTS_DIR. This identifies the subject that is to be processed. The input file, unless indicated otherwise, shoudl be located in $SUBJECTS_DIR/$s/mprage.nii.gz before processing is started.</explanation>
      <argument>--age age_in_months</argument>
      <explanation>Age of the FreeSurfer subject that is to be processed. </explanation>
      <argument>--newborn</argument>
      <explanation>This flag indicates that the subject to be processed is a newborn. All newborn subjects from the training data set will be used. No age input is needed if this flag is set. By default this flag is set to 0.</explanation>

    </required-flagged>
    
    <optional-flagged>

      <argument>--kneigh num</argument>
      <explanation>Number of training subjects to be used to acquire prior information about segmentation. Default is set to 4. </explanation>

      <argument>--outdir directory</argument>
      <explanation>Name of the output directory where all the reconall results are written. The default is $SUBJECTS_DIR/$s/, where $s is the subject id of the subject to be reconned. </explanation>

      <!argument>--aparc</argument>
      <!explanation>This option indicates that the tarining subjects have cortical parcellations. </explanation>

      <argument>--masked masked_input_image</argument>
      <explanation>This flag indicates that there exists a skullstripped version of the input image and that should be used as the input. This means that the skull-stripping step is skipped during the processing.</explanation>

      <argument>--force</argument>
      <explanation></explanation>

      <!argument>--avoidtraining</argument>
      <!explanation></explanation>

      <argument>--MI</argument>
      <explanation></explanation>

      <argument>--gmwm2</argument>
      <explanation></explanation>


      <intro>Cleanup Arguments</intro>
      <argument>--nocleanup</argument>
      <explanation>Do not delete temporary files (default is 0). If this option is set, make sure you have ~2G space in the output directory.</explanation>
      <argument>--keepelreg</argument>

    </optional-flagged>
  </arguments>

  <outputs>
    <intro>******************************************************************</intro>
    <intro>Full infant_recon_all pipeline</intro>

  </outputs>

  <bugs>None</bugs>

  <reporting>Report bugs to &lt;freesurfer@nmr.mgh.harvard.edu&gt;</reporting>

  <references>
  
  THESE TWO

  </references>

	<see-also></see-also>

</help>
